### ISSUE TITLE
Dropdown menu broken on smaller window sizes

### ISSUE THREAD

**Issue by agarrharr** [chrisanthropic/comical-jekyll-theme#1]
The dropdown works fine when I have the window as large as I can on my 15 inch screen. But if I make it a little smaller (about a third of that size), then when I hover over the submenu (dropdown), it immediately disappears and I can't click on anything.

I'm only trying this on your demo site. I haven't installed the theme yet.

**Comment by chrisanthropic** [comment]
Are you using Chrome? I've found that the 'hide-for-small' and 'hide-for-large' classes don't play well with chrome when resizing the window, but if you check it with the dev tools it displays properly.

**Comment by agarrharr** [comment]
It breaks in Chrome, Safari, and Firefox on Mac OS X Yosemite.

**Comment by agarrharr** [comment]
And it looks like your slim-pickins theme has the same issue. https://github.com/chrisanthropic/slim-pickins-jekyll-theme

**Comment by chrisanthropic** [comment]
I can't reproduce it here on my linux boxes on multiple screen sizes. Doesn't seem like it'd be an OS issue though. Thanks for the heads up, I'll look into it and see if I can figure out what's going on. 

Can you see if the same issue happens on this site? http://www.shamseecomic.com

**Comment by agarrharr** [comment]
Yes, it has the same issue. Also, your Gumroad and Amazon links to go http://www.shamseecomic.com

**Comment by chrisanthropic** [comment]
Yeah, I didn't have a dropdown in the menu on that site so I added one real quick. I just fixed the code to work with dropdown external urls.

Still, I can't reproduce the original issue. I've checked multiple windows sizes/resolutions across both of my home machines as well as my phone/tablet.

**Comment by chrisanthropic** [comment]
I was able to recreate the issue on a VM with OSX - I pushed a fix but could you please verify on your machine?

**Comment by agarrharr** [comment]
Yeah, it works now. Great job!

**Comment by chrisanthropic** [comment]
Sweet, thanks for the feedback.
